[package]
name = "derive-c-marshalling-library"
version = "0.1.0"
authors = ["Johan Gardell <736172+gardell@users.noreply.github.com>"]
edition = "2018"

[dependencies]
libc = "0.2.62"
syn = "1.0.5"
quote = "1.0.2"
