[package]
name = "derive-c-marshalling-library"
version = "0.1.0"
edition = "2018"
authors = ["Johan Gardell <736172+gardell@users.noreply.github.com>"]

[dependencies]
libc = "0.2"
syn = "1.0"
quote = "1.0"
proc-macro2 = "1.0"
