[package]
name = "generator"
version = "2.0.0"
edition = "2018"
authors = ["Johan Gardell <736172+gardell@users.noreply.github.com>"]

[dependencies]
syn = "1.0"
quote = "1.0"
proc-macro2 = "1.0"
parser = { path = "../parser" }
