[package]
name = "generator"
version = "0.1.0"
authors = ["Johan Gardell <736172+gardell@users.noreply.github.com>"]
edition = "2018"

[dependencies]
quote = "0.4"
syn = "0.12"
parser = { path = "../parser" }
