[package]
name = "lua-marshalling"
version = "0.1.0"
authors = ["Johan Gardell <736172+gardell@users.noreply.github.com>"]
edition = "2018"

[dependencies]
libc = "0.2.20"
c-marshalling = { path = "../c-marshalling" }
derive-lua-marshalling = { path = "../derive-lua-marshalling" }
