[package]
name = "parser"
version = "0.1.0"
authors = ["Johan Gardell <736172+gardell@users.noreply.github.com>"]
edition = "2018"

[dependencies]
syn = { version = "1.0.5", features = ["full"] }
quote = "1.0.2"
