[package]
name = "parser"
version = "0.2.0"
edition = "2018"
authors = ["Johan Gardell <736172+gardell@users.noreply.github.com>"]

[dependencies]
quote = "1.0"
proc-macro2 = "1.0"
syn = { version = "1.0", features = ["full"] }
