[package]
name = "parser"
version = "0.2.0"
edition = "2018"
authors = ["Johan Gardell <736172+gardell@users.noreply.github.com>"]

[dependencies]
quote = "0.4"
syn = { version = "0.12", features = ["full"] }
